### ISSUE TITLE
Doesn't work with Leaflet 1.0.3

### ISSUE THREAD

**Issue by MatixYo** [ebrelsford/Leaflet.snogylop#8]

**Comment by ebrelsford** [comment]
@MatixYo I believe the most recent release should take care of this--give it a shot and let me know?

**Comment by ebrelsford** [comment]
Assuming this is fixed since it works for me and I haven't heard back. Feel free to re-open if needed.

**Comment by onkartibe** [comment]
Seems this is still an issue. I am using 

`"leaflet": "^1.5.1",`
`"leaflet-draw": "^1.0.4"`

**Comment by ebrelsford** [comment]
@onkartibe This sounds like a different issue than the original one here--a few years back this plugin didn't work with Leaflet 1.x at all, now it does as you can see in the [examples](https://github.com/ebrelsford/Leaflet.snogylop/tree/master/examples/1.0). If you're running into an issue where it doesn't work, please create a new issue and provide a minimal example we can look at to determine the cause.
